# Generated by Django 2.0.4 on 2019-07-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateField(auto_now=True, verbose_name='issue creation date')),
                ('modified_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('bug_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bug_tracker.Bug')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('submitter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='employee_id',
            field=models.ForeignKey(on_delete=models.SET('none'), to='bug_tracker.Employee'),
        ),
        migrations.AddField(
            model_name='bug',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bug_tracker.Result'),
        ),
        migrations.AddField(
            model_name='bug',
            name='submitter_name',
            field=models.ForeignKey(on_delete=models.SET('none'), to='bug_tracker.Submitter'),
        ),
    ]
