# Generated by Django 2.0.4 on 2019-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
