# Generated by Django 2.0.4 on 2019-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_auto_20190830_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitter',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
