# Generated by Django 2.0.4 on 2019-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_auto_20190722_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
